In [1]:
import numpy as np

In [3]:
x = np.ones((3,3))
b = np.ones(3)
c = x+b
print(c)

[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


In [5]:
x = np.arange(9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
y = x*(x*(1-x))

In [7]:
print(y)

[[   0    0   -4]
 [ -18  -48 -100]
 [-180 -294 -448]]


In [8]:
print(x*(1-x))

[[  0   0  -2]
 [ -6 -12 -20]
 [-30 -42 -56]]


In [9]:
print(1-x)

[[ 1  0 -1]
 [-2 -3 -4]
 [-5 -6 -7]]


In [10]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
N = 4
K = 3
J = 6
delta_k = np.arange(N*K).reshape((N,K))
print(delta_k)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
W = np.arange(J*K).reshape(J,K)
print(W)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [15]:
G_p = np.ones((N,J))*4
print(G_p)

[[ 4.  4.  4.  4.  4.  4.]
 [ 4.  4.  4.  4.  4.  4.]
 [ 4.  4.  4.  4.  4.  4.]
 [ 4.  4.  4.  4.  4.  4.]]


In [27]:
print(np.dot(delta_k[0],W.transpose()))

[ 5 14 23 32 41 50]
